### ISSUE TITLE
Socks5服务器主动关闭导致无法再连接?

### ISSUE THREAD

**Issue by LazyZhu** [XiaoxiaoPu/sans#1]
![2015-03-04_211016](https://cloud.githubusercontent.com/assets/2244967/6484063/46cb9ace-c2b3-11e4-8a13-6bf64042d17d.png)

Update: 测试了Linux版没有此问题!

mingw编译版本:
http://dl.lazyzhu.com/file/Toolchain/sans_0.3.0_win32.zip

**Comment by puxxustc** [comment]
我这里无法重现这个 bug，但是问题应该不在 SOCKS5 服务器上，错误是 recvfrom 引起的，用于接受 UDP 包，而与 SOCKS5 服务器的通信是 TCP。你再试试能不能重现 bug，看看 bug 触发条件是什么。

**Comment by LazyZhu** [comment]
重现 bug很容易, 就是闲置一段时间后就会出现,可能SS远程关闭连接,sans一直尝试/重用这个连接导致的?

@XiaoxiaoPu mingw 交叉编译遇到2个问题

```
# make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /cross/mingw32/src/sans/auto/missing aclocal-1.15
/cross/mingw32/src/sans/auto/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127
```

可以通过 `touch configure.ac aclocal.m4 configure Makefile.am Makefile.in` 解决

```
i686-w64-mingw32-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -pipe -W -Wall -fno-strict-aliasing -O2 -pipe -MT mem.o -MD -MP -MF .deps/mem.Tpo -c -o mem.o mem.c
mv -f .deps/mem.Tpo .deps/mem.Po
i686-w64-mingw32-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -pipe -W -Wall -fno-strict-aliasing -O2 -pipe -MT sans.o -MD -MP -MF .deps/sans.Tpo -c -o sans.o sans.c
sans.c: In function 'reply_recv_cb':
sans.c:443:19: error: 'EINPROGRESS' undeclared (first use in this function)
sans.c:443:19: note: each undeclared identifier is reported only once for each function it appears in
sans.c: In function 'query_recv_cb':
sans.c:583:18: error: 'EINPROGRESS' undeclared (first use in this function)
sans.c: At top level:
sans.c:303:13: warning: 'accept_cb' defined but not used [-Wunused-function]
sans.c:63:14: warning: 'w_tcp' defined but not used [-Wunused-variable]
make[2]: *** [sans.o] Error 1
make[2]: Leaving directory `/cross/mingw32/src/sans/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/cross/mingw32/src/sans'
make: *** [all] Error 2
```

在[此处](https://github.com/XiaoxiaoPu/sans/blob/master/src/socks5.h#L26)添加了`#  define EINPROGRESS WSAEWOULDBLOCK` 才编译通过的

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 现在参数server不支持非53端口?

**Comment by puxxustc** [comment]
1. Bug 应该与 SS 无关，因为通过 SOCKS5 进行 DNS 查询时是短连接，每次查询都是新建连接，查询完就关掉的，我回头再试试能不能在我的电脑上重现这个 Bug
2. 这是因为你的 `aclocal` 版本比我的低，可以在 `configure` 前执行 `autoreconf -i -f`
3. [我自己编译没问题的](https://jenkins.xiaoxiao.im/job/sans/)，应该跟 MinGW 的版本有关，我会处理一下
4. 支持，server 字段的格式是 `ip:port`

**Comment by LazyZhu** [comment]
谢谢, latest commit 1,2,3 都解决了.
但是4的server的端口还是有问题,尝试了OpenDNS的5353/443端口以及自己VPS上pdnsd的DNS都不行,只有53端口可行:

```
listen=127.0.0.1:53
cn_server=114.114.114.114:53
server=208.67.222.222:5353
```

使用了sock5也不行:

```
listen=127.0.0.1:53
socks5=127.0.0.1:5380
cn_server=114.114.114.114:53
server=208.67.222.222:5353
```

以上配置只要改成`server=208.67.222.222:53`就正常.

**Comment by puxxustc** [comment]
@LazyZhu 因为非 53 端口不受 DNS 污染影响，因此 sans 用于判断域名是否被污染的方法就不起作用。

**Comment by LazyZhu** [comment]
建议改成判断的话用cn_server,或者用addr+53
其实最关键的问题是非53不工作

另外可以编译debug版吗？

**Comment by puxxustc** [comment]
@LazyZhu 加了一个 test_server 专门用于判断域名是否被污染，可以用下面的配置：

``` ini
listen=127.0.0.1:53
socks5=127.0.0.1:5380
test_server=8.8.8.8:53
cn_server=114.114.114.114:53
server=208.67.222.222:5353
```

编译 Debug 版：

``` bash
./configure --enable-debug
```

Debug 版会添加 `-g -DDEBUG -fprofile-arcs -ftest-coverage -O0`

**Comment by LazyZhu** [comment]
感谢, win下貌似还有问题,我编译debug版测试下.

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 出现这两个,域名就无法解析了.

![2015-03-08_183051](https://cloud.githubusercontent.com/assets/2244967/6545427/ade27c80-c5c1-11e4-8234-ad5550c486af.png)

![2015-03-08_185122](https://cloud.githubusercontent.com/assets/2244967/6545480/3d39d4e4-c5c4-11e4-9d93-03dfc8afc895.png)

http://dl.lazyzhu.com/file/Toolchain/sans_0.4.0_win32.zip

**Comment by puxxustc** [comment]
@LazyZhu 你的网络环境是什么样的？

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 电信

**Comment by puxxustc** [comment]
@LazyZhu 我是说网络拓扑，比如路由器上有没有 port redirect 之类的？

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 测试使用的路由没有对dns/翻墙做过设置

**Comment by puxxustc** [comment]
@LazyZhu 第一张图片的 Bug 重现条件是什么？

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 未知,突然就这样了
第二张图是时间长了就这样,现在又出现了,必须重开
![2015-03-08_203905](https://cloud.githubusercontent.com/assets/2244967/6545788/71a6b54e-c5d3-11e4-86ce-58bbb57d5ee1.png)

**Comment by puxxustc** [comment]
@LazyZhu 你有没有修改过 query.c 里面的 QUERY_QUEUE_LEN? 另外第 2 个 BUG 我一直没法重现......

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 没有修改过, 这个bug一直使用了一个半小时才出现, 有时候又很快出现:
![2015-03-08_205805](https://cloud.githubusercontent.com/assets/2244967/6545843/069b343e-c5d6-11e4-80f4-a6be64b08c1c.png)

socks5使用的是https://github.com/shadowsocks/shadowsocks-csharp

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 这次信息比较多
![2015-03-08_211915](https://cloud.githubusercontent.com/assets/2244967/6545932/7f74348e-c5d9-11e4-9a2b-55f10a3cc8f0.png)

**Comment by puxxustc** [comment]
@LazyZhu 已经发现了一些问题，正在改。另外第 2 个 Bug 是 [Winsocks 的问题](http://www.cnblogs.com/leading/archive/2012/06/24/udp-connection-reset-10054-under-windows.html)，正在找解决办法。

**Comment by puxxustc** [comment]
@LazyZhu 对代码进行了大规模的重构，可以试一试。另外因为换了电脑，所以 MinGW 平台还没测试。

**Comment by LazyZhu** [comment]
@XiaoxiaoPu OK
