### ISSUE TITLE
musl下运行报错

### ISSUE THREAD

**Issue by qiuzi** [XiaoxiaoPu/sans#10]
Assertion failed: sock > 0 (dnsmsg.c: query_recv: 74)
这是启动得到的报告

**Comment by puxxustc** [comment]
无法重现，贴出配置和完整的 log

**Comment by qiuzi** [comment]
log就这些 
配置还是之前一样 不过musl还处于不稳定阶段 有兴趣你再研究吧

**Comment by puxxustc** [comment]
我用 openwrt i486 musl 测试没问题，大概是编译工具链的问题吧
