### ISSUE TITLE
间歇性判断故障

### ISSUE THREAD

**Issue by qiuzi** [XiaoxiaoPu/sans#12]
使用境外测试DNS服务器会受到超时和阻断，造成SANA不能正常工作 重启程序只能维持10分钟

**Comment by puxxustc** [comment]
使用 root dns server

**Comment by qiuzi** [comment]
有些网络会限制，与服务器没关系，能不能同时请求多个服务器来判断 对于这样的故障抓包能看出来吗？

**Comment by puxxustc** [comment]
任何网络都不应该限制对 root dns server 的访问，gfw 也不会

**Comment by qiuzi** [comment]
移动网络你懂的

**Comment by qiuzi** [comment]
如果按你说的这样那解析一直等待是什么原因？nslookup xxx.xxx 8.8.8.8又能正常
