### ISSUE TITLE
MinGW: sys/select.h: No such file or directory

### ISSUE THREAD

**Issue by LazyZhu** [XiaoxiaoPu/sans#3]
```
i686-w64-mingw32-gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..    -pipe -fno-strict-aliasing -Wall -W -Wshadow -Wwrite-strings -Wcast-qual -g -O2 -MT event.o -MD -MP -MF .deps/event.Tpo -c -o event.o event.c
event.c:23:24: fatal error: sys/select.h: No such file or directory
 #include <sys/select.h>
                        ^
compilation terminated.
Makefile:347: recipe for target 'event.o' failed
make[2]: *** [event.o] Error 1
```

**Comment by LazyZhu** [comment]
Winsocks 的问题貌似还没解决?
另外能否添加个小功能, 支持打印blocked域名到文件.

**Comment by puxxustc** [comment]
看看最新的 commit 有没有修复 winsocks 的问题（没 Windows 没法测试）。打印 blocked 域名是为了什么呢？把 log 重定向到文件然后用脚本处理一下也是可以的吧？

**Comment by LazyZhu** [comment]
@XiaoxiaoPu 

> 打印 blocked 域名是为了什么呢？

收集 blocked 域名是为了配合Dnsmasq,下次就不用检测了

> 把 log 重定向到文件然后用脚本处理一下也是可以的吧？

Windows下不能用, Linux下的verbose信息量太多,不适合日常使用.

另外,我做成了OpenWRT包,目前只有二进制,init和luci过两天加.

**Comment by puxxustc** [comment]
这个功能我有时间做一下吧，暂时不放到 master 上，新开个分支。另外以后有新问题还是新开 issue 比较好，方便跟踪、记录。OpenWrt 我不是很熟，你测试好了可以把相关文件放到 contrib/openwrt 里，提个 pull request ;-)
